### PR TITLE
do not backup when no player was online since the last backup

### PR DESCRIPTION
**Pull request by NikkyAI**
still missing config.. but why would you want to disable this ?

### CODE REVIEW

**Comment by phit** [comment]
because chunkloaders? plenty of reasons, please add a config and disable it by default

**Comment by alexbobp** [comment]
Thanks for working on this!  I want to reiterate what phit said... this definitely can't be the default behavior.  Right now your patch looks good aside from that, so let me know if you'd like me to config-ize it myself.

**Comment by NikkyAI** [comment]
of course.. the comment was mainly some misplaced humour.. thats all the features i had time to implement for the day.. i will add the next feature soon

**Comment by NikkyAI** [comment]
i added the config implementation and checged it from a boolean flag to a countdown
you can keep any number of backups after no player is online.. -2 or lower will keep all backups,
i am slightly concerned how to handle if people enter -1 or 0 in the config..
that would make the logic think the countdown is up on every backup,
maybe just add validation or fixing to the config
if the value is -1 or 0 make sure it is set to 1

**Comment by NikkyAI** [comment]
well i reverted the number junk

**Pull request merged**
